{application,elixir_tic_tac_toe,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"elixir_tic_tac_toe"},
              {modules,['Elixir.Board','Elixir.Computer',
                        'Elixir.ElixirTicTacToe','Elixir.Game',
                        'Elixir.Player']},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger]}]}.
